[package]
name = "proof_age"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.19.0"

[dependencies]
date = { path = "/Users/madztheo/Documents/Wagmi/Studio/RnD/Docaproof/noir-libs/noir_date" }